### PR TITLE
Implementing Search

### PR DESCRIPTION
**Pull request by jack-makers**

### CODE REVIEW

**Review by jack-makers — COMMENTED** [review]
search

**Review by jack-makers — COMMENTED** [review]
search

**Review by jack-makers — COMMENTED** [review]
added display name for book title

**Review by jack-makers — COMMENTED** [review]
search

**Review by willj4945 — APPROVED** [review]
Approved for merge

**Review by lesowi93 — APPROVED** [review]

**Review by madoged — APPROVED** [review]
Approve for merge

**Pull request merged**
